# Libraries

## NumPy

In [1]:
import numpy as np # generally imported as np

In [2]:
#create 1D array

arr_1d = np.array([1,2,3,4])
print(arr_1d)
print()

[1 2 3 4]



In [3]:
from numpy import array # importing the whole library mi

In [4]:
arr_1d = array([1,2,3,4])
print(arr_1d)
print()

[1 2 3 4]



## you can shorten up more


In [5]:
from numpy import array as ar
arr_1d = ar([1,2,3,4])
print(arr_1d)
print()

[1 2 3 4]



In [6]:
#create 2D array
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#reshape array
arr_1d = np.array([1,2,3,4,5,6,7,8])
print(arr_1d)

arr_2d = arr_1d.reshape(2,4)
print(arr_2d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#add value to all elements
print(arr_1d)
print(arr_1d + 2)

[1 2 3 4 5 6 7 8]
[ 3  4  5  6  7  8  9 10]


In [9]:
#multiply each element by 3

print(arr_2d)
print(arr_2d * 2)

[[1 2 3 4]
 [5 6 7 8]]
[[ 2  4  6  8]
 [10 12 14 16]]


In [10]:
[1,2,3,4]*2 # it duplicate the list 

[1, 2, 3, 4, 1, 2, 3, 4]

In [11]:
#sum all elements in np.array()
np.sum(arr_2d)

36

In [12]:
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [13]:
np.sum(arr_2d, axis=0)

array([ 6,  8, 10, 12])

In [14]:
np.sum(arr_2d, axis=1)

array([10, 26])

In [15]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
#slicing 1D , up to 4 but not including
arr_1d[1:4]

array([2, 3, 4])

In [17]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
#slicing 2D, up to 4 but not including
arr_2d[1,1:4]

array([6, 7, 8])

In [19]:
#boolean indexing, which values match some criteria

arr_2d % 2 ==  0

array([[False,  True, False,  True],
       [False,  True, False,  True]])

In [20]:
#boolean mask

arr_2d[arr_2d % 2 ==  0]

array([2, 4, 6, 8])

In [21]:
#functions on arrays

np.mean(arr_1d)

4.5

In [22]:
#functions on arrays

np.std(arr_1d)

2.29128784747792

In [23]:
#array generation: empty array 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
#array generation: array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
#array generation: identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
#sequence : similar ro range function, start, stop and step value
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
#sequence : similar ro range function, start, stop and step value (not include the stop value)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
#grid of values: start, stop and how many evenly spaced sample you want, calculated over the interval [start, stop] 
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [29]:
#combine functions: grid of values -> reshape
np.linspace(0, 2, 6).reshape(3,2)

array([[0. , 0.4],
       [0.8, 1.2],
       [1.6, 2. ]])

In [30]:
#combine functions: grid of values -> reshape
np.linspace(0, 2, 6).reshape(2,2)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [ ]:
# Define two vectors A and B
A = np.array([2, 3, 4])
B = np.array([5, 6, 7])

# Calculate the dot product A · B
dot_product_AB = np.dot(A, B)

# Calculate the dot product B · A
dot_product_BA = np.dot(B, A)

# Check if the dot products are equal (commutative property)
if dot_product_AB == dot_product_BA:
    print('A · B = B · A')
    print(f'A · B = {dot_product_AB}')
else:
    print('A · B is not equal to B · A')

## Pandas

In [ ]:
import pandas as pd # genarally imported as pd

In [ ]:
#create dataframe

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)

# Create a DataFrame from a list of dictionaries
data_list = [{'Name': 'Alice', 'Age': 25},
             {'Name': 'Bob', 'Age': 30},
             {'Name': 'Charlie', 'Age': 35}]
df = pd.DataFrame(data_list)
df

In [ ]:
#https://www.uniprot.org/locations?query=nucleus

nucleus_loci = pd.read_csv('locations_nucleus.tsv', sep='\t')
nucleus_loci

In [ ]:
# function to see the first rows, here first 5 rows
nucleus_loci.head(n=5)

In [ ]:
#subset columns , two square brackets
nucleus_loci[['Name', 'Category']].head()

In [ ]:
#subset rows: iloc method
nucleus_loci.iloc[1:4,:]

In [ ]:
#drop na
nucleus_loci = nucleus_loci.dropna()

#if inplace:
nucleus_loci.dropna(inplace=True)

In [ ]:
#select NaN -> change to another value 'Other'

In [ ]:
#select specific col: output is series, one-dimensiona version of dataframe
nucleus_loci['Is a']

In [ ]:
#select rows of col that are NaN
nucleus_loci['Is a'].isna()

In [ ]:
#filter whole df based on boolean values
#AKA boolean mask

mask = nucleus_loci['Is a'].isna()

nucleus_loci['Is a'][mask] = 'Other'

nucleus_loci['Is a']

In [ ]:
## calling a column
nucleus_loci.Name
nucleus_loci['Name']

In [ ]:
# another mask

mask = (nucleus_loci.Name == 'Cytoplasm') | (nucleus_loci.Name == 'Target cell cytoplasm')

nucleus_loci[mask]

In [ ]:
# another mask

mask = nucleus_loci['Name'].str.contains('cytoplasm')

nucleus_loci[mask]

In [ ]:
# another mask (or symbol)

mask = nucleus_loci['Name'].str.contains('Cytoplasm') | nucleus_loci['Name'].str.contains('cytoplasm')

nucleus_loci[mask]

In [ ]:
# In Pandas, the .str.lower() method is used to convert all characters in a string column to lowercase
# .upper() upper case .title() title case
mask = nucleus_loci['Name'].str.lower().str.contains('cytoplasm') 


nucleus_loci[mask]

Other things Pandas offers:

* time-series
* in built plotting
* merging and joining data
* more complex functions

## Matplotlib

In [ ]:
import matplotlib.pyplot as plt #for plotting needs

In [ ]:
# Data
x = [1, 2, 3, 4, 5]
y = [2, 4, 6, 8, 10]

# Create a line plot
plt.plot(x, y)

# Add labels and title
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Simple Line Plot')

# Show the plot
plt.show()
## search for syntax to save the figure and what formats been supported

In [ ]:
# create a figure with multiple subplots
fig, subfigs = plt.subplots()

#plot point
# Create a line plot
subfigs.plot(x, y)

# Add labels and title
subfigs.set_xlabel('X-axis')
subfigs.set_ylabel('Y-axis')
subfigs.set_title('Simple Line Plot')

In [ ]:
import random
# customize fig size, number of plots
fig, subfigs = plt.subplots(1,2, figsize=(12, 5))

#plot point
# select individual plots 
# Create a line plot
subfigs[0].plot(x, y)

# Add labels and title
subfigs[0].set_xlabel('X-axis')
subfigs[0].set_ylabel('Y-axis')
subfigs[0].set_title('Simple Line Plot')

#add to second plot
subfigs[1].scatter([random.randint(-10, 10) for x in range(10)], [random.randint(-10, 10) for x in range(10)], color='red')
# List comprehension offers a shorter syntax when you want to create a new list based on the values of an existing list
# Add labels and title
subfigs[1].set_xlabel('Other X-axis')
subfigs[1].set_ylabel('Y-axis')
subfigs[1].set_title('Simple Scatter Plot')

In [ ]:
import random
# sharey=True is an argument used with the plt.subplots() function to create subplots with a shared y-axis. 
# This means that all subplots in the same row or column (depending on how you've organized your subplots) will have the same y-axis scale and limits
fig, subfigs = plt.subplots(1,2, figsize=(12, 5), sharey=True)

#plot point
# Create a line plot
subfigs[0].plot(x, y)

# Add labels and title
subfigs[0].set_xlabel('X-axis')
subfigs[0].set_ylabel('Y-axis')
subfigs[0].set_title('Simple Line Plot')

#add to second plot
subfigs[1].scatter([random.randint(-10, 10) for x in range(10)], [random.randint(-10, 10) for x in range(10)], color='red')
# Add labels and title
subfigs[1].set_xlabel('Other X-axis')
subfigs[1].set_ylabel('Y-axis')
subfigs[1].set_title('Simple Scatter Plot')

In [ ]:
!conda install numpy
!pip install numpy